name: Build and Create Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag for the new release (e.g., v1.1.0)'
        required: true
      release_title:
        description: 'Title of the release'
        required: true
      release_body:
        description: 'Description for the release'
        required: false
permissions:
  contents: write
jobs:
  build-x86:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_keyword: "linux-64"
            os_path: "linux-x64"
            ext: ""
          - os: windows-latest
            asset_keyword: "windows-64"
            os_path: "windows-x64"
            ext: ".exe"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Checkout sub-checker python files
        uses: actions/checkout@v4
        with:
          repository: arshiacomplus/sub-checker
          path: sub-checker
          sparse-checkout: |
            cl.py
            python_v2ray
            requirements.txt
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt
          if [ -f sub-checker/requirements.txt ]; then pip install -r sub-checker/requirements.txt; fi
      - name: Download Core Binaries
        shell: bash
        run: |
          mkdir -p sub-checker/vendor
          XRAY_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/XTLS/Xray-core/releases/latest" | grep "browser_download_url.*${{ matrix.asset_keyword }}.zip" | cut -d '"' -f 4 | head -n 1)
          if [ -z "$XRAY_URL" ]; then echo "::error::Could not find Xray-core URL." && exit 1; fi
          curl -L -o xray.zip "$XRAY_URL"
          if [ "${{ runner.os }}" == "Windows" ]; then 7z x xray.zip -o"sub-checker/vendor" xray.exe geosite.dat geoip.dat; else unzip -o xray.zip -d sub-checker/vendor xray geosite.dat geoip.dat; fi
          rm xray.zip
          chmod +x sub-checker/vendor/* || true
      - name: Set output file names
        id: set_names
        shell: bash
        run: |
          OS_PATH=${{ matrix.os_path }}
          EXE_EXT=${{ matrix.ext }}
          echo "EXE_NAME=v2ray_scraper_ui_${OS_PATH}${EXE_EXT}" >> $GITHUB_ENV
          echo "ASSET_NAME=v2ray_scraper_ui_${OS_PATH}.zip" >> $GITHUB_ENV
      - name: Compile with Nuitka
        shell: bash
        run: |
          export PYTHONPATH=$PYTHONPATH:./sub-checker
          python -m nuitka main.py --onefile --output-dir=dist --output-filename=${{ env.EXE_NAME }} --follow-imports   --include-data-dir=app/web=app/web --include-data-dir=sub_checker=sub_checker --assume-yes-for-downloads --include-module=jinja2
      - name: Compress executable
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then 7z a ${{ env.ASSET_NAME }} ./dist/${{ env.EXE_NAME }}; else zip -j ${{ env.ASSET_NAME }} ./dist/${{ env.EXE_NAME }}; fi
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-asset-${{ matrix.os_path }}
          path: ${{ env.ASSET_NAME }}
  release:
    needs: [build-x86]
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_title }}
          body: ${{ github.event.inputs.release_body }}
          files: artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}